app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::group(['middleware' => ['web','auth.basic']], function () {
    Route::get('contact', [
        'as' => 'contact', 'uses' => 'ContactController@viewContact'
    ]);
    Route::post('contact', [
        'as' => 'post_contact', 'uses' => 'ContactController@postContact'
    ]);
});
Route::resource('photo', 'PhotoController');
Route::singularResourceParameters();
Route::resourceParameters([
    'photo' => 'image'
]);
Route::resource('member', 'MemberSearchController');
Route::resource('post_search', 'PostSearchController');
Route::auth();

Route::get('/home', [
    'middleware' => ['api','auth'],'as'=>'home',
    'uses' => 'HomeController@index'
]);
Route::get('profile', [
    'middleware' => 'auth:api',
    'uses' => 'ProfileController@show'
]);

Route::group(['middleware' => ['guest']], function () {
    //Login Routes...
    Route::get('/admin/login','AdminAuth\AuthController@showLoginForm');
    Route::post('/admin/login','AdminAuth\AuthController@login')->name('login');
    Route::get('/admin/logout','AdminAuth\AuthController@logout');

    // Registration Routes...
    Route::get('admin/register', 'AdminAuth\AuthController@showRegistrationForm');
    Route::post('admin/register', 'AdminAuth\AuthController@register');
    Route::get('admin/users/forgot', 'AdminAuth\PasswordController@getEmail');
    Route::post('admin/users/forgot', 'AdminAuth\PasswordController@postEmail');
    Route::get('/admin', 'AdminController@index');

});

app/Http/Controllers/PhotoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Contracts\EventPusher;

class PhotoController extends Controller
{


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(EventPusher $pusher)
    {
        echo url()->current()."<br/>";
        /* use bind */
        $bind = app('printAge');
        $bind->setUsername('khanhdq119@gmail.com');
        echo $bind->getUsername()."<br/>";
        $bind1 = app('printAge');
        echo $bind1->getUsername()."<br/>";
        /* use bind */

        /* use singleton */
        $singleton = app('printMyName');
        $singleton->setUsername('khanhdq119@rocketmail.com');
        echo $singleton->getUsername()."<br/>";
        $singleton1 = app('printMyName');
        echo $singleton1->getUsername()."<br/>";
        /* use singleton */
        echo $pusher->cronJobSendMail();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $jobs = ['teacher','doctor','engineer','worker'];
        $date = time();
        return view('photo.index',['jobs'=>$jobs,'date'=>$date]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //$request->flash();
        return redirect()->back()->with([
            'status' => 'test 11111111111','abc'=>'aaaaa',
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        echo route('photo.show',['id'=>1])."<br/>";
        echo route('photo.edit',['id'=>1])."<br/>";
        echo route('photo.update',['id'=>1])."<br/>";
        echo route('photo.destroy',['id'=>1])."<br/>";
    }

    /**
     * Show the form for editing the specified resource.
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        //
        echo $id."<br/>";
        echo $request->cookie('username');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        echo "Email 1: ".$request->input('email.0')."<br/>";
        echo "Email 2: ".$request->input('email.1')."<br/>";
        echo "Get all: ".var_dump($request->all())."<br/>";
        //
        echo $request->method()."<br/>";
        if ($request->isMethod('post')) {
            echo "use request->isMethod('post')"."<br/>";
        }
        echo $request->url()."<br/>";
        echo $request->fullUrl()."<br/>";
        if ($request->is('photo')) {
            echo "ok"."<br/>";
        } else {
            echo "fail"."<br/>";
        }
        echo $request->fullUrlWithQuery(['bar' => 'baz'])."<br/>";
        echo url()->current()."<br/>";
        echo $id."<br/>";
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        echo "destroy ".$id."<br/>";
    }
}

resources/views/photo/empty.blade.php
empty blade

resources/views/photo/index.blade.php
@extends('layouts/master')
@section('sidebar')
    @parent
    <p>This is appended to the master sidebar.</p>
@endsection
@section('content')
    <?php var_dump($errors->all()); ?>
    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif
    <form id="form_login_email" method="post" action="{{route('photo.store')}}">
        <input type="hidden" name="_token" value="<?php echo csrf_token(); ?>">
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" autofocus="" class="form-control" value="{{ old('username') }}" name="username"
                   id="username" tabindex="2" autocapitalize="off">
        </div>
        <div class="form-group">
            <label for="username">Email 1</label>
            <input type="text" autofocus="" class="form-control" value="" name="email[]"
                   id="username" tabindex="2" autocapitalize="off">
        </div>
        <div class="form-group">
            <label for="username">Email 2</label>
            <input type="text" autofocus="" class="form-control" value="" name="email[]"
                   id="username" tabindex="2" autocapitalize="off">
        </div>
        <div class="error errorMessage-text js-loginError">&nbsp;</div>
        <div>
            <button class="submit btn btn-warning btn-raised" type="submit" id="submit_login_email" tabindex="4">Log
                in
            </button>
        </div>
    </form>
    {{-- This comment will not be present in the rendered HTML --}}
    //@each('photo.view', $jobs, 'job','photo.empty')
    <p>@datetime($date)</p>
    @inject('metrics', 'App\Services\MetricsService')
    <div>
        Monthly Revenue: {{ $metrics->monthlyRevenue() }}.
    </div>
@endsection
@push('scripts')
<script type="text/javascript">
    alert("test push script");
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
@endpush

resources/views/photo/view.blade.php
<li>{{$job}}</li>